version: '2'
services: 
  redis-server:
    image: 'redis'
  node-app:
    labels:
      io.rancher.scheduler.affinity:host_label: newhost=newhost

    image: rajeshworld/node:latest
    ports:
      - "4041:8081"

