version: '2'
services: 
  redis-server:
    image: 'redis'
  node-app:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: newhost=newhost
      io.rancher.container.network: true
    image: rajeshworld/node:latest
    ports:
      - "4041:8081"

